### ISSUE TITLE
搜索引擎

### ISSUE THREAD

**Issue by dazhuangge** [liuzhuoling2011/music-jojo#10]
搜索引擎最后可以歌曲歌手同时搜索这样更好匹配

**Comment by liuzhuoling2011** [comment]
![image](https://user-images.githubusercontent.com/8407297/52607343-e6a1dc80-2eb0-11e9-8e1f-047b8137d1e2.png)
一直都可以同时搜索，搜索结果跟各个平台的搜索结果基本一致
