### ISSUE TITLE
提供一个自建QQ音乐接口

### ISSUE THREAD

**Issue by liumingye** [liuzhuoling2011/music-jojo#15]
高品 http://ftp6289422.host111.sanfengyun.cn/?id=M800{songmid}.mp3
无损 http://ftp6289422.host111.sanfengyun.cn/?id=F000{songmid}.flac

http://ftp6289422.host111.sanfengyun.cn/?id=F000101bqRIc495LxO.flac

![批注 2019-05-15 202023.jpg](http://ww1.sinaimg.cn/large/64877dfcly1g329t45sy7j21hb06tmzj.jpg)

必须传递cookie，zhujiwusysdomain=ftp6289422.host111.sanfengyun.cn
不传递 打不开页面

**Comment by liuzhuoling2011** [comment]
谢谢提供
之前使用了别人的接口， 结果后来人家不愿意让开源使用了，一下子就尴尬了
所以你的接口是开源的嘛？我有些顾虑

**Comment by liumingye** [comment]
代码就几条，不过需要有绿钻的Cookie

<?php
$id = $_GET['id'];

$curl = curl_init();

curl_setopt($curl, CURLOPT_URL, 'https://c.y.qq.com/base/fcgi-bin/fcg_music_express_mobile3.fcg?loginUin=0&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0&cid=205361747&uin=0&songmid=002u8ZOM4C7QF4&filename=' . $id . '&guid=lmy');

//需要绿钻的Cookie
$header = array(
	'Cookie: p_luin=; p_lskey=;',
);

curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);

$response = curl_exec($curl);
curl_close($curl);

$Data = json_decode($response, true);
echo 'http://mobileoc.music.tc.qq.com/' . $_GET['id'] . '?guid=lmy&uin=0&vkey=' . $Data['data']['items'][0]['vkey'];

**Comment by liumingye** [comment]
`<?php
$id = $_GET['id'];

$curl = curl_init();

curl_setopt($curl, CURLOPT_URL, 'https://c.y.qq.com/base/fcgi-bin/fcg_music_express_mobile3.fcg?loginUin=0&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0&cid=205361747&uin=0&songmid=002u8ZOM4C7QF4&filename=' . $id . '&guid=lmy');

//需要开通绿钻的Cookie
$header = array(
	'Cookie: p_luin=; p_lskey=;',
);

curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);

$response = curl_exec($curl);
curl_close($curl);

$Data = json_decode($response, true);
echo 'http://mobileoc.music.tc.qq.com/' . $_GET['id'] . '?guid=lmy&uin=0&vkey=' . $Data['data']['items'][0]['vkey'];`

**Comment by liuzhuoling2011** [comment]
印象中绿钻下载的高品质音乐是有限制的？

**Comment by liuzhuoling2011** [comment]
印象中绿钻下载的高品质音乐是有数量限制的？
cookie应该很快就过期了吧。。。这样会不会接口不稳定

**Comment by liumingye** [comment]
QQ自检测songmid=002u8ZOM4C7QF4

**Comment by liumingye** [comment]
我看cookie一个月才过期
QQ只检测songmid=002u8ZOM4C7QF4，songmid是免费下载的就不会扣下载配额，而且付费专辑也能免费下载

**Comment by liuzhuoling2011** [comment]
我是想把搜索， 下载的api直接集成到app里面， 这样不需要中心服务器，软件使用体验也会很快
如果app里面的api需要经常更新，事情就会麻烦了

**Comment by liuzhuoling2011** [comment]
你好, 你的服务现在还可以用吗

**Comment by yydmss** [comment]
> 
> 
> 代码就几条，不过需要有绿钻的Cookie

您好请问是y.qq.com的cookie吗，好像木有找到p_luin=; p_lskey=这俩名称的
