### ISSUE TITLE
暂无数据

### ISSUE THREAD

**Issue by WhitLor** [liuzhuoling2011/music-jojo#2]
愉快地下歌途中突然搜索任何关键词都提示暂无数据，之前集中在网易云通道下载了25首，卸载重新安装恢复正常，是有意设置成这样的吗？

**Comment by liuzhuoling2011** [comment]
代码都是开源的，没有这样的设置哈
可能是后台服务器压力过大，过一会儿再试

**Comment by WhitLor** [comment]
感谢解答
