### ISSUE TITLE
bug一枚

### ISSUE THREAD

**Issue by WhitLor** [liuzhuoling2011/music-jojo#3]
![image](https://user-images.githubusercontent.com/34998894/51580390-408d3300-1eff-11e9-9971-f2e6d7598d7a.png)
应该是文件名包含特殊字符，同类软件先下载后改名，名字会乱码，但是歌仍会下载到本地

**Comment by WhitLor** [comment]
对，就是那个问号
![image](https://user-images.githubusercontent.com/34998894/51580539-cf9a4b00-1eff-11e9-9ed9-cfe8eaff7356.png)

**Comment by liuzhuoling2011** [comment]
收到，感谢
